### ISSUE TITLE
Are you going to continue with this mod?

### ISSUE THREAD

**Issue by ghost** [jamesxsc/Theatrical#9]
I am a theatre tech and would love to see this mod through.. i built the current version and I am assuming there is not actually a way to get the current lights to actually light up...

Anyways please continue with this mod as it is exactly what I have been looking for!

**Comment by Rushmead** [comment]
Hi @jnawotka 

First of all we have now moved to this github repository: https://github.com/theatricalmod/theatrical-forge on the 1.15.1 branch.

I'm glad that you like the idea of this mod! I'm actively still working on it, I've got the basics of a lighting console on my local development environment. I'm hoping to have that done soon.

We currently have a discord server that you can join where we sometimes discuss the progress and updates in the mod,  the link to that is here: https://discord.gg/7qMs5d6

I also often stream development on my twitch channel.

**Comment by ghost** [comment]
That is Great To Hear!

I have joined the Discord!
